[package]
name = "redland-rs"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]

[dependencies]
libc = "~0.2.44"
serde_derive = "~1.0.89"
serde = "~1.0.89"

[dev-dependencies]
bincode = "~1.1.2"

[build-dependencies]
bindgen = "~0.43.2"
